#!/usr/bin/env bash

# This script is used to build the JITOO project.
# It is intended to be run from the root of the repository.
# It will build the project in the current directory.
# It will also create a build directory and place the build artifacts there.
# It will also create a release directory and place the release artifacts there.


login="sshpass -p StartOurDream2022 ssh posapp@116.193.191.104"
help() {
    echo "$(tput setaf 3)
    Name: jitoo
    Developer: Malikkurosaki@2022<kurosakiblackangel@gmail.com>
    Version: 1.0
    Usage: ./jitoo [options]
    Options:
    -h, help: Print this help message
    -rs, runs: run server
    -rc, runc: run client
    -b, build: build project client
   $(tput sgr0)"
}

perintah1() {
    case $1 in
    runs | -rs) cd xsvr && nodemon svr.js ;;
    runc | -rc) flutter run -d chrome --web-renderer html ;;
    build | -b) flutter build web --release ;;
    mig | -m) prisma migrate dev --name $tm && prisma generate ;;
    push | -p)
        git add .
        git commit -m "push"
        git push -u origin main
        $login -t "cd ~/kamitri && git pull origin main && cd ~/kamitri/xsvr/ && ./build_server"
        ;;
    *) echo "./jitoo [ parameter ] -[ $1 ] belum ada" ;;
    esac
}

if [ $# -eq 1 ]; then
    perintah1 $1
else
    help
fi
