-- AlterTable
ALTER TABLE `Nota` ADD COLUMN `diUpdet` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `dibuat` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `NotaDetail` ADD COLUMN `diBuat` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `diUpdet` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
